version: "3.9"

networks:
  web:
    external: true
  internal:
    external: false

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.prod
      args:
        POETRY_VERSION: ${POETRY_VERSION}
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    environment:
      API_ENV: prod
      API_PORT: ${API_PORT}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD_HASHED: /run/secrets/admin_password_hash
      SECRET_KEY: /run/secrets/api_secret
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: /run/secrets/db_passwd
      DB_NAME: ${DB_NAME}
      SPOTIFY_ID: ${SPOTIFY_ID}
      SPOTIFY_SECRET: /run/secrets/spotify_secret
      SPOTIFY_REDIRECT: ${SPOTIFY_REDIRECT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.playlist_api.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.playlist_api.tls=true"
      - "traefik.http.routers.playlist_api.tls.certresolver=lets-encrypt"
      - "traefik.http.services.playlist_api.loadbalancer.server.port=${API_PORT}"
    networks:
      - internal
      - web
    volumes:
      - ${PWD}/api/.cache:/app/.cache
    secrets:
      - api_secret
      - admin_password_hash
      - db_passwd
      - spotify_secret
  client:
    build:
      context: client
      dockerfile: Dockerfile.prod
      args:
      CLIENT_PORT: ${CLIENT_PORT}
      API_URL: "http://api:${API_PORT}"
      SERVER_URL: "http://server:${SERVER_PORT}"
      NEXT_PUBLIC_SPOTIFY_CLIENT_ID: ${SPOTIFY_APP_ID}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      API_URL: "http://api:${API_PORT}"
      CLIENT_PORT: ${CLIENT_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.playlist_client.rule=Host(`${CLIENT_HOST}`)"
      - "traefik.http.routers.playlist_client.tls=true"
      - "traefik.http.routers.playlist_client.tls.certresolver=lets-encrypt"
      - "traefik.http.services.playlist_client.loadbalancer.server.port=${CLIENT_PORT}"
    networks:
      - internal
      - web
    depends_on:
      - api

secrets:
  api_secret:
    file: api.secret
  spotify_secret:
    file: spotify.secret
  admin_password_hash:
    file: admin.secret
  db_passwd:
    file: db.secret