services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
      args:
        POETRY_VERSION: ${POETRY_VERSION}
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      API_ENV: dev
      API_PORT: ${API_PORT}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD_HASHED: /run/secrets/admin_password_hash
      SECRET_KEY: /run/secrets/api_secret
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: /run/secrets/db_passwd
      DB_NAME: ${DB_NAME}
      SPOTIFY_ID: ${SPOTIFY_ID}
      SPOTIFY_SECRET: /run/secrets/spotify_secret
      SPOTIFY_REDIRECT: ${SPOTIFY_REDIRECT}
    volumes:
      - ./api/src:/app/src
      - ${PWD}/api/.cache:/app/.cache
    secrets:
      - api_secret
      - admin_password_hash
      - db_passwd
      - spotify_secret
  # client:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile.dev
  #     args:
  #       API_URL: "http://api:${API_PORT}"
  #       CLIENT_PORT: ${CLIENT_PORT}
  #   ports:
  #     - "${CLIENT_PORT}:${CLIENT_PORT}"
  #   environment:
  #     API_URL: "http://api:${API_PORT}"
  #     CLIENT_PORT: ${CLIENT_PORT}
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./client:/app
  #     - ./client/node_modules:/app/node_modules

secrets:
  api_secret:
    file: api.secret
  spotify_secret:
    file: spotify.secret
  admin_password_hash:
    file: admin.secret
  db_passwd:
    file: db.secret